---
title: "`r params$GameTitle` Game Design Document"
params:
  GameTitle: "Solara"
  GamePredator: "hero"
  GamePrey: "beasts" # decide whether to use beast, demon, monster, etc.
format: 
  html:
    toc: true
    other-links: 
      - text: Project tasks and timeline
        href: https://github.com/users/niboXR/projects/3
        icon: github
---

```{r, setup}
#| include: false
```

# Overview

## Game description

**`{r} params$GameTitle`** is a stylized open-globe action-adventure fantasy game with support for up to 64 simultaneous players and built from the ground up for physical immersion.

The world of `{r} params$GameTitle` falls increasingly to darkness. The residents have abandoned their homes for shelter within the last standing city of `{r} params$GameTitle`. The majority of the population has turned into mindless `{r} params$GamePrey`. You awaken as a resident of `{r} params$GameTitle`. Does the will of a `{r} params$GamePredator` or the will of `{r} params$GamePrey` awaken with you?

Take on the world alone or form an adventurer's guild in a fantastical, yet-dangerous, quest to eradicate darkness and retake `{r} params$GameTitle`. Explore the land to discover lost treasures, uncover knowledge, and unravel its mysteries. Perfect your trade or become a jack of all trades. You determine your path.

## Inspirations

Zelda: Breathe of the Wild is an illustrious open-world action adventure game with some basic RPG elements. The simple, yet compelling style and mechanics contributes to a world that breathes.

OG virtual reality rpg games like Zenith: The Last City, Karnage Chronicles, and Vengeful Rites that first immersed me in fantasy worlds.

No Mans Sky, while it took some time, eventually demonstrated the incredible power of procedural generation. Their implementation has resulted in a mind-bending sci-fi exploration game that has captivated me for hundreds of hours.


##### The goal is to learn from the successes and failures of early virtual reality games and apply the programming wizardry of procedural world-building in pursuit of infinite immersive worlds as compelling as Hyrule.

# Design

## Character

Characters are humanoids that exist in the world, both playable and non-playable. Players create their characters using a custom character creator. 

### Character stats

These stats apply to *all* characters

#### Physical stats

A character has three physical stats:

-   **Vitality** - determines how much damage a character can take. A character's base vitality stat is **100** life points.

-   **Strength** - determines how much damage a character can deal. A character's base strength stat is **10** damage. This means that a fully effective blow will deal **10** points in damage to another character's vitality or an item's durability.

-   **Speed** - determines how quickly a character can move. A character's base walking speed is **INSERT WLK_SPD** and base running speed is **INSERT RUN_SPD**.

Base physical stat values are weighted based on the character build [^1]. @tbl-1 provides discrete examples of the impact character BMI [^2] has on a character's physical stats.

[^1]: This design is inspired by Bonelab's avatar system and intended to incentivize thoughtful and diverse character creation.

[^2]: Body Mass Index is calculated from a person's height and weight. While this measure is considered imperfect for real-world applications, it provides a single measure from which base stats can be derived.

Physical stats can be further modified via items.

#### Standing

A character's standing indicates their threat and morality to others. The two standing stats are:

-   **Level** - an evolving measure of a character's accomplishments. It is derived from enemy encounter outcomes. A character's default and minimum level is **1**. The maximum level is **100**.

-   **Karma** - an evolving measure of a character's deeds. It is derived from your actions. The quests you take on, the enemies you kill, and even your environmental impact will dictate your place in this world. Karma ranges from **DARK** to **HERO** with a default value of **NEUTRAL**. Characters can also have **GOOD** or **BAD** karma.


##### Karmic Justice {#sec-justice}
Creating a world with karmic justice requires deep consideration of the actions that deserve karmic penalties and the consequences of accumulating bad karma penalties. 

###### Karmic penalties

-   Character killing and looting
-   Taking on and completing dark quests
-   Resource overconsumption and waste

###### Karmic consequences

-   Loss of safe zone and housing
-   Increased drop rates
-   Bounties

## Environment

A procedural system for the creation of unique and infinitely difficult worlds[^3]. The globe is fully navigable with diverse landscapes, wildlife, and `r params$GamePrey`.

[^3]: A procedural system combines parameters for switching between categorical values and random sampling for continuous values. Note that available parameters and probability curves will likely be impacted by other values.

### Resources

All resources can be gathered the environment. The resource types are:

-   **resources** - various types and qualities of wood, ore, and fibers

-   **ingredients** - various types and qualities of meat, fish, vegetation, and herbs

Resources can be gathered and crafted into items by characters engaging in various professions.

### Items

Items can be discovered throughout the world or crafted from resources gathered from the environment. The item types are:

-   **wearables** are crafted from resources by outfitters

-   **consumables** are crafted from ingredients by cooks and from resources by alchemists

-   **tools** are crafted from resources by toolmakers

@tbl-2 provides examples for the types and kinds of items found in `r params$GameTitle`.

Items have varying **durability** which can be restored through crafting. Unneeded items can also be sold or broken down for partial resources. 

Item **rarity** is based on global inventory, see @tbl-3 below for rarity calculations. In addition to item rarity, items produced using resources from a parallel world are considered *exotic* when the resources are not natively available.

## Economy

### Professions {#sec-professions}

There are various professions in resources gathering and crafting that characters will encounter. Each profession will have distinct and compelling mechanics and quest lines. 

Foragers, hunters, anglers, miners, and loggers are the professions will learn how to gather natural resources and ingredients from the environment, while outfitters, toolmakers, cooks, and alchemists craft these resources into valuable items.


### Trade

Resources and items can be traded between characters on the open market or privately. Historical sale prices are public record at the server level.

One currency, forever.

# Gameplay


## Dungeons, encampments, and strongholds


## Events


## Quests


## World Bosses




# Tables and Figures

## Impact of character build on physical stats

+-----------+----------+----------+---------+
| Character | Vitality | Strength | Speed   |
|           |          |          |         |
| BMI       |          |          |         |
+===========+==========+==========+=========+
| Low       | ➖       | 🔻       | 🔺      |
+-----------+----------+----------+---------+
| Med       | ➖       | ➖       | ➖      |
+-----------+----------+----------+---------+
| High      | 🔺       | 🔺       | 🔻🔻    |
+-----------+----------+----------+---------+

: Impact of character build on physical stats\
🔺stat boost ➖no change 🔻stat penalty {#tbl-1}


## The types and kinds of items
+----------------+---------------------+------------------------------+
| Types          | Kinds               | Examples                     |
+================+=====================+==============================+
| Wearable       | headwear\           | `brass helmet`\              |
|                | topwear\            | `dark tunic`\                |
|                | legwear\            | `leather pants`\             |
|                | footwear            | `leather boots`              |
+----------------+---------------------+------------------------------+
| Consumable     | food\               | `beef stew`\                 |
|                | elixer              | `elixer of life`             |
+----------------+---------------------+------------------------------+
| Tool           | sword\              | `long sword`\                |
|                | shield\             | `wooden shield`\             |
|                | fishing pole\       | `bamboo fishing pole`\       |
|                | pickaxe\            | `iron pickaxe`\              |
|                | axe                 | `stone axe`                  |
+----------------+---------------------+------------------------------+

: The types and kinds of items\
{#tbl-2}

## Item rarities

| Rarity    | Color  | Threshold                                      |
|-----------|--------|------------------------------------------------|
| Common    | White  | The item makes up no more than 25% of its kind |
| Uncommon  | Green  | The item makes up less than 25% of its kind    |
| Rare      | Blue   | The item makes up less than 5% of its kind     |
| Legendary | Purple | The item makes up less than 1% of its kind     |
| Unique    | Gold   | The only item of its kind in the world         |

: Item rarities\
{#tbl-3}
